name: Build CloudStream Plugins

on:
  push:
    branches:
      - master # O la rama principal de tu repositorio (main, etc.)

jobs:
  build:
    runs-on: ubuntu-latest # O una imagen de Android/Java si es más específica, pero ubuntu-latest suele funcionar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Usa la acción de checkout para obtener tu código

      - name: Set up JDK 17 # Configura Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # Cachea las dependencias de Gradle para compilaciones más rápidas

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # Asegura que el script de Gradle sea ejecutable

      - name: Build Plugins # ¡Este es el paso clave para compilar tus plugins!
        run: ./gradlew assemble # Ejecuta la tarea 'assemble' de Gradle para construir todos los módulos

      - name: Upload Plugins Artifact # Sube los plugins compilados como un artefacto de la acción
        uses: actions/upload-artifact@v4
        with:
          name: cloudstream-plugins # Nombre del artefacto
          path: 'plugins/' # La carpeta donde se supone que Gradle genera los .cs3 (asegúrate de que sea correcta)
          # También puedes especificar la ruta completa si es build/outputs/cs3/ para cada módulo,
          # por ejemplo, path: 'ExampleProvider/build/outputs/cs3/'
          # Si tienes varios plugins, podrías necesitar una estrategia para colectarlos.
          # Por ahora, asumiendo que tu build.gradle.kts raíz los copia a la carpeta 'plugins/'
          # Si no es así, deberías añadir un paso de copia en tu build.gradle.kts o aquí.

      - name: Deploy Plugins to GitHub Pages (Optional - if you want to automate this)
        uses: peaceiris/actions-gh-pages@v3 # Puedes usar esta acción para subir los plugins a GitHub Pages
        if: github.ref == 'refs/heads/master' # Solo en el push a master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: plugins # La carpeta que contiene tus .cs3 para subir a GitHub Pages
          # CUIDADO: esto podría sobreescribir otros archivos si tu 'plugins' folder no es exclusiva para .cs3
          # Considera crear una carpeta '_plugins_build' y subir solo eso.