name: Publicar Plugins CloudStream

on:
  push:
    branches:
      - master # o la rama principal de tu código fuente (ej: main)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4 # Asegura que se checkout la rama actual (master/main)

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir Plugins
        run: |
          cd $GITHUB_WORKSPACE/src # Cambia al directorio del código fuente
          chmod +x gradlew # Otorga permisos de ejecución al script gradlew
          ./gradlew clean make makePluginsJson --refresh-dependencies # Ejecuta las tareas de Gradle
          
          # Copia el repo.json y plugins.json a la raíz del repositorio (rama master)
          # Esto los hará accesibles vía raw.githubusercontent.com
          cp build/repo.json $GITHUB_WORKSPACE/repo.json
          cp build/plugins.json $GITHUB_WORKSPACE/plugins.json # Si también se usa plugins.json

          # Asegura que la carpeta 'plugins' exista en la raíz del repositorio
          # y copia los .cs3 allí. El repo.json ya espera esta ruta.
          mkdir -p $GITHUB_WORKSPACE/plugins
          cp **/build/*.cs3 $GITHUB_WORKSPACE/plugins/ || true

        shell: bash

      - name: Subir archivos generados a GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Publicar archivos de CloudStream (repo.json, plugins.json, .cs3) en raw.githubusercontent.com'
          # Los archivos se subirán a la misma rama que activó el workflow (master/main)