name: Publicar Plugins CloudStream

on:
  push:
    branches:
      - master # <--- ¡IMPORTANTE! Cambia esto a 'main' si esa es tu rama principal.

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir Plugins
        run: |
          # El script 'gradlew' y el 'build.gradle.kts' principal
          # están en la raíz del repositorio, así que no es necesario 'cd'
          chmod +x gradlew # Otorga permisos de ejecución al script gradlew
          ./gradlew clean make makePluginsJson --refresh-dependencies # Ejecuta las tareas de Gradle
          
          # Copia el repo.json y plugins.json generados por Gradle a la raíz del repositorio.
          # Esto los hará accesibles vía raw.githubusercontent.com/<tu_usuario>/<tu_repo>/master/repo.json
          cp build/repo.json . 
          cp build/plugins.json . # Copia plugins.json si también lo necesitas para tu repositorio

          # Asegura que la carpeta 'plugins' exista en la raíz del repositorio
          # y copia todos los archivos .cs3 generados allí.
          # El repo.json generado por el plugin de CloudStream esperará esta ruta.
          mkdir -p plugins
          cp **/build/*.cs3 plugins/ || true

        shell: bash

      - name: Subir archivos generados a GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Publicar archivos de CloudStream (repo.json, plugins.json, .cs3) en raw.githubusercontent.com'
          # Esta acción subirá automáticamente los archivos copiados en los pasos anteriores
          # a la misma rama que activó el workflow (master/main).